// LCA II explicitly allows p/q to be absent. Missing selectors are actual
// detached node objects, while present selectors retain original root identity.
import{generateFunctionRunnerTemplate}from'./functionRunnerTemplateService.js';
import{buildFunctionInputPayload,materializeFunctionInputPlaceholders}from'./functionTestInputService.js';
const type=x=>String(x||'').trim().replace(/^(['"])(.*)\1$/,'$2').toLowerCase();
export function isAbsentIdentityTreeSelectorProblem(p){const c=p?.functionContract;return ['Lowest Common Ancestor of a Binary Tree II','Lowest Common Ancestor Of A Binary Tree Ii'].includes(p?.title)&&p.executionMode==='function'&&c?.kind!=='stateful'&&c.className==='Solution'&&c.methodName==='lowestCommonAncestor'&&['tree-node','treenode'].includes(type(c.returnType))&&c.parameters?.length===3&&c.parameters.map(x=>x.name).join(',')==='root,p,q'&&c.parameters.every(x=>['tree-node','treenode'].includes(type(x.type)))&&c.outputMode!=='parameter';}
export function validateAbsentIdentityTreeSelectorFixture(problem,input){if(!isAbsentIdentityTreeSelectorProblem(problem))throw Error('Exact LCA II root/p/q node contract required');const args=buildFunctionInputPayload(input,problem.functionContract).args,[values,p,q]=args,integer=x=>Number.isSafeInteger(x)&&x>=-1e9&&x<=1e9;if(args.length!==3||!Array.isArray(values)||!values.length||!integer(values[0])||values.some(x=>x!==null&&!integer(x))||!integer(p)||!integer(q)||p===q)throw Error('Unique root tree and distinct scalar node selectors required');const seen=new Set([values[0]]),queue=[values[0]];let cursor=1;for(let head=0;head<queue.length&&cursor<values.length;head++)for(let child=0;child<2&&cursor<values.length;child++){const value=values[cursor++];if(value===null)continue;if(seen.has(value))throw Error('Ambiguous duplicate tree node value');seen.add(value);queue.push(value);}if(values.slice(cursor).some(x=>x!==null))throw Error('Unreachable tree node values');if(seen.size>10000)throw Error('LCA II tree exceeds source node bound');return{values,p,q,nodeCount:seen.size,bothPresent:seen.has(p)&&seen.has(q)};}
export function validateAbsentIdentityTreeSelectorOutput(problem,input,output){const fixture=validateAbsentIdentityTreeSelectorFixture(problem,input);const text=String(output).trim();if(!fixture.bothPresent){if(!['None','null'].includes(text))throw Error('An absent selector requires null output');return fixture;}let expected;try{expected=JSON.parse(text);}catch{throw Error('Present selectors require serialized returned subtree');}if(!Array.isArray(expected)||!expected.length||expected[0]===null||expected.some(x=>x!==null&&(!Number.isSafeInteger(x)||x<-1e9||x>1e9)))throw Error('Present selectors require serialized returned subtree');return fixture;}
export function prepareAbsentIdentityTreeSelectorSource(language,problem,userCode,input){const fixture=validateAbsentIdentityTreeSelectorFixture(problem,input),className='Solution',adapterClass='PeerPrepAbsentTreeSelectorAdapter',method='peerPrepAbsentSelectedAncestor';let adapter,code=String(userCode);
 if(language==='python'){const marker='# PeerPrep generated function adapter. Keep this section unchanged.',index=code.indexOf(marker);if(index>=0&&/^class\s+Solution\s*:/m.test(code.slice(0,index)))code=code.slice(0,index).trimEnd();adapter=`\ndef peerPrepSelectAbsentNode(root,value):\n    queue=[root]\n    for node in queue:\n        if node.val==value: return node\n        if node.left is not None: queue.append(node.left)\n        if node.right is not None: queue.append(node.right)\n    return TreeNode(value)\nclass ${adapterClass}(${className}):\n    def ${method}(self,root,p,q):\n        return self.lowestCommonAncestor(root,peerPrepSelectAbsentNode(root,p),peerPrepSelectAbsentNode(root,q))\n`;}
 if(language==='javascript'||language==='typescript'){const ts=language==='typescript',any=ts?':any':'',number=ts?':number':'',uncommented=code.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/[^\r\n]*/g,''),call=/\bclass\s+Solution\b/.test(uncommented)?'new Solution().lowestCommonAncestor':'lowestCommonAncestor';adapter=`\nfunction peerPrepSelectAbsentNode(root${any},value${number})${any}{const queue${any}=[root];for(let head=0;head<queue.length;head++){const node=queue[head];if(node.val===value)return node;if(node.left!=null)queue.push(node.left);if(node.right!=null)queue.push(node.right);}return new TreeNode(value);}\nfunction ${method}(root${any},p${number},q${number})${any}{return ${call}(root,peerPrepSelectAbsentNode(root,p),peerPrepSelectAbsentNode(root,q));}\n`;}
 if(language==='cpp')adapter=`\nclass ${adapterClass}:public Solution{public:static TreeNode* select(TreeNode* root,int value){vector<TreeNode*> queue{root};for(size_t head=0;head<queue.size();head++){TreeNode* node=queue[head];if(node->val==value)return node;if(node->left)queue.push_back(node->left);if(node->right)queue.push_back(node->right);}return new TreeNode(value);}TreeNode* ${method}(TreeNode* root,int p,int q){return lowestCommonAncestor(root,select(root,p),select(root,q));}};\n`;
 if(language==='java'){code=code.replace(/(^|\n)\s*public\s+class\s+Solution\b/,'$1class Solution');adapter=`\nclass ${adapterClass} extends Solution{static TreeNode select(TreeNode root,int value){java.util.ArrayList<TreeNode> queue=new java.util.ArrayList<>();queue.add(root);for(int head=0;head<queue.size();head++){TreeNode node=queue.get(head);if(node.val==value)return node;if(node.left!=null)queue.add(node.left);if(node.right!=null)queue.add(node.right);}return new TreeNode(value);}public TreeNode ${method}(TreeNode root,int p,int q){return lowestCommonAncestor(root,select(root,p),select(root,q));}}\n`;}
 if(language==='c'){code=code.replace(/\bstruct\s+TreeNode\s*\{[^}]*\}\s*;/gs,'');adapter=`\nstatic struct TreeNode* ppSelectAbsentNode(struct TreeNode* root,int value){struct TreeNode** queue=malloc(sizeof(struct TreeNode*)*${fixture.nodeCount});int count=1;queue[0]=root;for(int head=0;head<count;head++){struct TreeNode* node=queue[head];if(node->val==value){free(queue);return node;}if(node->left)queue[count++]=node->left;if(node->right)queue[count++]=node->right;}free(queue);struct TreeNode* detached=calloc(1,sizeof(struct TreeNode));detached->val=value;return detached;}struct TreeNode* ${method}(struct TreeNode* root,int p,int q){return lowestCommonAncestor(root,ppSelectAbsentNode(root,p),ppSelectAbsentNode(root,q));}\n`;}
 if(!adapter)throw Error('LCA II requires a supported six-language runner');const adapted={...problem.functionContract,className:adapterClass,methodName:method,parameters:[{name:'root',type:'tree-node'},{name:'p',type:'integer'},{name:'q',type:'integer'}],returnType:'tree-node',outputMode:'return',runnerLanguage:language},injected=code+adapter,template=generateFunctionRunnerTemplate(language,adapted,injected);if(!template)throw Error('Missing LCA II private runner');return materializeFunctionInputPlaceholders(template,input,adapted).replace('{{USER_CODE}}',injected);
}
