import {generateFunctionRunnerTemplate} from './functionRunnerTemplateService.js';import {materializeFunctionInputPlaceholders} from './functionTestInputService.js';import {validateAdditiveExpressionFixture} from './additiveExpressionFixtureService.js';
export function prepareAdditiveExpressionSource(language,p,userCode,input){const f=validateAdditiveExpressionFixture(p,input),method='peerPrepProvidedAdditiveExpressions',adapterClass='PeerPrepAdditiveExpressionAdapter';let code=String(userCode),prefix='',adapter='';
 if(language==='python'){const marker=code.indexOf('# PeerPrep generated function adapter. Keep this section unchanged.');if(marker>=0)code=code.slice(0,marker);prefix='class Node:\n    def __init__(self,val=" ",left=None,right=None): self.val=val;self.left=left;self.right=right\n';adapter=`\nclass ${adapterClass}(Solution):\n    def ${method}(self,rows1,rows2):\n        def build(rows):\n            nodes=[Node(chr(row[0])) for row in rows]\n            for i,row in enumerate(rows):\n                nodes[i].left=nodes[row[1]] if row[1]>=0 else None\n                nodes[i].right=nodes[row[2]] if row[2]>=0 else None\n            return nodes[0]\n        return self.checkEquivalence(build(rows1),build(rows2))\n`;}
 if(language==='javascript'||language==='typescript'){const ts=language==='typescript',type=ts?'_Node':'Node',plain=code.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/[^\r\n]*/g,''),call=/\bclass\s+Solution\b/.test(plain)?'new Solution().checkEquivalence':'checkEquivalence';prefix=ts?'class _Node{constructor(public val:string=" ",public left:_Node|null=null,public right:_Node|null=null){}}\n':'class Node{constructor(val=" ",left=null,right=null){this.val=val;this.left=left;this.right=right;}}\n';adapter=`\nfunction ${method}(rows1${ts?':number[][]':''},rows2${ts?':number[][]':''})${ts?':boolean':''}{function build(rows${ts?':number[][]':''}){const nodes=rows.map(row=>new ${type}(String.fromCharCode(row[0])));for(let i=0;i<rows.length;i++){nodes[i].left=rows[i][1]<0?null:nodes[rows[i][1]];nodes[i].right=rows[i][2]<0?null:nodes[rows[i][2]];}return nodes[0];}return ${call}(build(rows1),build(rows2));}\n`;}
 if(language==='cpp'){prefix='class Node{public:char val;Node*left,*right;Node(char v=\' \',Node*l=nullptr,Node*r=nullptr):val(v),left(l),right(r){}};\n';adapter=`\nclass ${adapterClass}:public Solution{Node*build(vector<vector<int>>&rows){vector<Node*>nodes;for(auto&row:rows)nodes.push_back(new Node((char)row[0]));for(size_t i=0;i<rows.size();i++){nodes[i]->left=rows[i][1]<0?nullptr:nodes[rows[i][1]];nodes[i]->right=rows[i][2]<0?nullptr:nodes[rows[i][2]];}return nodes[0];}public:bool ${method}(vector<vector<int>>rows1,vector<vector<int>>rows2){return checkEquivalence(build(rows1),build(rows2));}};\n`;}
 if(language==='java'){code=code.replace(/(^|\n)\s*public\s+class\s+Solution\b/,'$1class Solution');prefix='class Node{char val;Node left,right;Node(){this(\' \');}Node(char v){val=v;}Node(char v,Node l,Node r){val=v;left=l;right=r;}}\n';adapter=`\nclass ${adapterClass} extends Solution{Node build(int[][]rows){Node[]nodes=new Node[rows.length];for(int i=0;i<rows.length;i++)nodes[i]=new Node((char)rows[i][0]);for(int i=0;i<rows.length;i++){nodes[i].left=rows[i][1]<0?null:nodes[rows[i][1]];nodes[i].right=rows[i][2]<0?null:nodes[rows[i][2]];}return nodes[0];}public boolean ${method}(int[][]rows1,int[][]rows2){return checkEquivalence(build(rows1),build(rows2));}}\n`;}
 if(language==='c'){code=code.replace(/\bstruct\s+Node\s*\{[^}]*\}\s*;/gs,'');prefix='struct Node{char val;struct Node*left,*right;};\n';adapter=`\nstatic struct Node*ppBuildExpression(int**rows,int n){struct Node**nodes=malloc(n*sizeof(*nodes));for(int i=0;i<n;i++){nodes[i]=malloc(sizeof(**nodes));nodes[i]->val=(char)rows[i][0];}for(int i=0;i<n;i++){nodes[i]->left=rows[i][1]<0?NULL:nodes[rows[i][1]];nodes[i]->right=rows[i][2]<0?NULL:nodes[rows[i][2]];}struct Node*root=nodes[0];free(nodes);return root;}\nbool ${method}(int**rows1,int rows1Size,int*rows1ColSize,int**rows2,int rows2Size,int*rows2ColSize){return checkEquivalence(ppBuildExpression(rows1,rows1Size),ppBuildExpression(rows2,rows2Size));}\n`;}
 if(!adapter)throw Error('Six-language provided expression Node adapter required');const contract={className:adapterClass,methodName:method,parameters:[{name:'rows1',type:'integer[][]'},{name:'rows2',type:'integer[][]'}],returnType:'boolean',outputMode:'return',runnerLanguage:language},injected=language==='java'?code+prefix+adapter:prefix+code+adapter,template=generateFunctionRunnerTemplate(language,contract,injected);if(!template)throw Error('Expression private numeric runner unavailable');return materializeFunctionInputPlaceholders(template,'rows1='+JSON.stringify(f.root1)+',rows2='+JSON.stringify(f.root2),contract).replace('{{USER_CODE}}',injected);
}
