import {buildFunctionInputPayload,parseFunctionTestInput} from './functionTestInputService.js';
export const additiveExpressionContract={className:'Solution',kind:'function',methodName:'checkEquivalence',parameters:[{name:'root1',type:'expression-node'},{name:'root2',type:'expression-node'}],returnType:'boolean',outputMode:'return'};
export function additiveExpressionRule(p){const c=p?.functionContract;return p?.title==='Check If Two Expression Trees are Equivalent'&&p.executionMode==='function'&&c?.className==='Solution'&&c.kind!=='stateful'&&c.methodName==='checkEquivalence'&&c.returnType==='boolean'&&c.outputMode!=='parameter'&&JSON.stringify(c.parameters?.map(x=>[x.name,x.type]))===JSON.stringify(additiveExpressionContract.parameters.map(x=>[x.name,x.type]))?{kind:'additive-expression'}:null;}
// Original examples use unquoted one-character Node labels. Quote only such
// list tokens; preserve quoted contents and all other input syntax exactly.
export function normalizeAdditiveExpressionInput(input){const source=String(input);let result='',quote='',escaped=false,depth=0;for(let i=0;i<source.length;i++){const c=source[i];if(quote){result+=c;if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c===quote)quote='';continue;}if(c==='"'||c==="'"){quote=c;result+=c;continue;}if(c==='[')depth++;if(c===']')depth--;if(depth>0&&/[a-z+]/.test(c)){let before=i-1;while(before>=0&&/\s/.test(source[before]))before--;const token=source.slice(i).match(/^([a-z+])(?=\s*[,\]])/);if(token&&['[',','].includes(source[before])){result+=JSON.stringify(c);continue;}}result+=c;}return result;}
function expression(rows){if(!Array.isArray(rows))throw Error('Source expression serialization required');const values=rows.slice();while(values.at(-1)===null)values.pop();if(!values.length||values[0]===null)throw Error('Nonempty source expression required');const nodes=[[String(values[0]).charCodeAt(0),-1,-1]],queue=[0],counts=Array(26).fill(0);let at=1;
 for(let q=0;q<queue.length;q++){const node=nodes[queue[q]],value=values[queue[q]===0?0:node[3]];if(typeof value!=='string'||!/^([a-z]|\+)$/.test(value))throw Error('Source plus operators and lowercase variable leaves required');for(const side of [1,2]){const child=at<values.length?values[at]:null,slot=at++;if(child!==null){node[side]=nodes.length;nodes.push([String(child).charCodeAt(0),-1,-1,slot]);queue.push(node[side]);}}
  if(value==='+'){if(node[1]<0||node[2]<0)throw Error('Every plus operator requires both operands');}else{if(node[1]>=0||node[2]>=0)throw Error('Variable nodes must be leaves');counts[value.charCodeAt(0)-97]++;}
 }
 if(at<values.length||nodes.length>4999||nodes.length%2!==1)throw Error('Complete source expression with at most4999 reachable nodes required');return{rows:nodes.map(x=>x.slice(0,3)),counts};
}
export function validateAdditiveExpressionFixture(p,input){if(!additiveExpressionRule(p))throw Error('Exact additive expression node contract required');const [root1,root2]=buildFunctionInputPayload(normalizeAdditiveExpressionInput(input),p.functionContract).args,a=expression(root1),b=expression(root2);if(a.rows.length!==b.rows.length)throw Error('Source trees require equal odd node counts');return{root1:a.rows,root2:b.rows,expected:a.counts.every((x,i)=>x===b.counts[i])};}
export function acceptsAdditiveExpressionOutput(p,tc,raw){if(!additiveExpressionRule(p))return null;try{const f=validateAdditiveExpressionFixture(p,tc.input),parsed=parseFunctionTestInput(String(raw).trim()).positional;return parsed.length===1&&typeof parsed[0]==='boolean'&&parsed[0]===f.expected;}catch{return false;}}
