import{parseFunctionTestInput,materializeFunctionInputPlaceholders}from'./functionTestInputService.js';
import{generateFunctionRunnerTemplate}from'./functionRunnerTemplateService.js';
import{parseNodeResultEnvelope,wrapVerifiedNodeCapture}from'./customNodeResultEnvelopeService.js';
export const QUAD_NODE_APIS=[
 {id:'6ac27fe850fef4f698aa20b6',sourceId:427,title:'Construct Quad Tree',methodName:'construct',parameters:[{name:'grid',type:'integer[][]'}]},
 {id:'6ac280399b62de7b23709642',sourceId:558,title:'Logical OR of Two Binary Grids Represented as Quad-Trees',methodName:'intersect',parameters:[{name:'quadTree1',type:'quad-node'},{name:'quadTree2',type:'quad-node'}]},
];
export const quadNodeContract=r=>({className:'Solution',methodName:r.methodName,parameters:r.parameters.map(v=>({...v})),returnType:'quad-node',outputMode:'return'});
export function quadNodeRule(p){const c=p?.functionContract;return QUAD_NODE_APIS.find(r=>p.executionMode==='function'&&p.title===r.title&&c?.className==='Solution'&&c.kind!=='stateful'&&c.methodName===r.methodName&&c.returnType==='quad-node'&&c.outputMode!=='parameter'&&c.parameters?.length===r.parameters.length&&c.parameters.every((v,i)=>v.name===r.parameters[i].name&&v.type===r.parameters[i].type))||null;}
export function decodeQuadTree(a){
 if(!Array.isArray(a)||!a.length||a.length>1398101||a[0]===null)throw Error('Quad tree requires a nonempty serialized root.');
 const nodes=[],depth=[],leaf=v=>Array.isArray(v)&&v.length===2&&v.every(x=>x===0||x===1);
 const add=(v,d)=>{if(!leaf(v)||d>9)throw Error('Invalid Quad flags or source depth.');nodes.push({isLeaf:v[0],val:v[1],children:[]});depth.push(d);return nodes.length-1;};
 add(a[0],0);let index=1;
 for(let parent=0;parent<nodes.length;parent++)for(let k=0;k<4;k++){
  const v=index<a.length?a[index++]:null;
  if(nodes[parent].isLeaf){if(v!==null)throw Error('Leaf quad children must be null.');}
  else{if(v===null)throw Error('Internal quad requires four children.');nodes[parent].children.push(add(v,depth[parent]+1));}
 }
 if(index<a.length)throw Error('Unattached quad serialization.');
 return{nodes,depth:depth.reduce((a,b)=>Math.max(a,b),0)};
}
function raster(tree,size){const pixels=new Uint8Array(size*size),stack=[[0,0,0,size]];while(stack.length){const[id,row,col,n]=stack.pop(),node=tree.nodes[id];if(node.isLeaf){for(let y=row;y<row+n;y++)pixels.fill(node.val,y*size+col,y*size+col+n);}else{if(n<2)throw Error('Quad subdivision exceeds raster size.');const h=n/2;for(let k=0;k<4;k++)stack.push([node.children[k],row+(k>>1)*h,col+(k%2)*h,h]);}}return pixels;}
function canonical(pixels,size){const nodes=[];function build(row,col,n){const id=nodes.length,bit=pixels[row*size+col];let same=true;for(let y=row;y<row+n&&same;y++)for(let x=col;x<col+n;x++)if(pixels[y*size+x]!==bit){same=false;break;}const node={isLeaf:same?1:0,val:same?bit:0,children:[]};nodes.push(node);if(!same){const h=n/2;for(let k=0;k<4;k++)node.children.push(build(row+(k>>1)*h,col+(k%2)*h,h));}return id;}build(0,0,size);return nodes;}
export function validateQuadNodeFixture(p,input){
 const rule=quadNodeRule(p);if(!rule)throw Error('Unsupported exact Quad Node public contract.');const parsed=parseFunctionTestInput(input),v=parsed.named;
 if(parsed.positional.length||Object.keys(v).length!==rule.parameters.length||rule.parameters.some(x=>!Object.hasOwn(v,x.name)))throw Error('Quad private arguments do not match public interface.');
 let grid,size,trees=[],pixels;
 if(rule.sourceId===427){grid=v.grid;size=grid?.length;if(!Array.isArray(grid)||!Number.isInteger(size)||size<1||size>64||(size&(size-1))||grid.some(r=>!Array.isArray(r)||r.length!==size||r.some(x=>x!==0&&x!==1)))throw Error('Construct Quad requires binary square power-of-two grid n1..64.');pixels=Uint8Array.from(grid.flat());}
 else{trees=rule.parameters.map(x=>decodeQuadTree(v[x.name]));size=2**Math.max(...trees.map(t=>t.depth));const a=raster(trees[0],size),b=raster(trees[1],size);pixels=Uint8Array.from(a,(x,i)=>x|b[i]);}
 return{rule,grid,size,trees,expected:canonical(pixels,size)};
}
function sameQuadShape(left,right){const stack=[[0,0]];while(stack.length){const[a,b]=stack.pop(),x=left[a],y=right[b];if(x.isLeaf!==y.isLeaf||x.isLeaf&&x.val!==y.val)return false;if(!x.isLeaf)for(let k=0;k<4;k++)stack.push([x.children[k],y.children[k]]);}return true;}
export function validateQuadNodeOracle(p,tc){try{return sameQuadShape(validateQuadNodeFixture(p,tc.input).expected,decodeQuadTree(JSON.parse(tc.output)).nodes);}catch{return false;}}
export function serializeQuadTree(nodes){const result=[],queue=[0];for(let i=0;i<queue.length;i++){const id=queue[i];if(id===null){result.push(null);continue;}const node=nodes[id];result.push([node.isLeaf,node.val]);queue.push(...(node.isLeaf?[null,null,null,null]:node.children));}while(result.at(-1)===null)result.pop();return result;}
export function acceptsQuadNodeOutput(p,tc,raw){if(!quadNodeRule(p))return undefined;const result=parseNodeResultEnvelope(raw);return !!result&&validateQuadNodeOracle(p,tc)&&validateQuadNodeOracle(p,{...tc,output:JSON.stringify(result.value)});}
const fields=['topLeft','topRight','bottomLeft','bottomRight'],uncom=v=>String(v).replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/[^\r\n]*/g,''),ar=a=>a.length?a.join(','):'0';
const ja=a=>{if(!a.length)return'new int[0]';const csv=a.join(','),chunks=[];for(let i=0;i<csv.length;i+=16000)chunks.push(JSON.stringify(csv.slice(i,i+16000)));return`java.util.Arrays.stream(String.join("",new String[]{${chunks.join(',')}}).split(",")).mapToInt(Integer::parseInt).toArray()`;};
const flat=nodes=>nodes.flatMap(v=>[v.isLeaf,v.val,...(v.isLeaf?[-1,-1,-1,-1]:v.children)]);
function nativeCapture(f,cpp){const n=f.expected.length,P=cpp?'Node*':'struct Node*',nil=cpp?'nullptr':'NULL';let prefix='',body='';
 function constructTree(t,j){prefix+=`static int _ppQuadInput${j}[]={${ar(flat(t.nodes))}};`;body+=`${P}input${j}[${t.nodes.length}];for(int i=0;i<${t.nodes.length};i++){input${j}[i]=${cpp?`new Node(_ppQuadInput${j}[6*i+1]!=0,_ppQuadInput${j}[6*i]!=0)`:'calloc(1,sizeof(struct Node))'};input${j}[i]->isLeaf=_ppQuadInput${j}[6*i]!=0;input${j}[i]->val=_ppQuadInput${j}[6*i+1]!=0;}for(int i=0;i<${t.nodes.length};i++){${fields.map((field,k)=>`input${j}[i]->${field}=_ppQuadInput${j}[6*i+${k+2}]<0?${nil}:input${j}[_ppQuadInput${j}[6*i+${k+2}]];`).join('')}}`;}
 let call;
 if(f.rule.sourceId===558){f.trees.forEach(constructTree);call=`${cpp?'Solution().':''}intersect(input0[0],input1[0])`;}
 else{prefix+=`static int _ppQuadGrid[]={${f.grid.flat().join(',')}};`;body+=cpp?`std::vector<std::vector<int>>grid(${f.size},std::vector<int>(${f.size}));for(int i=0;i<${f.size};i++)for(int j=0;j<${f.size};j++)grid[i][j]=_ppQuadGrid[i*${f.size}+j];`:`int*grid[${f.size}],widths[${f.size}];for(int i=0;i<${f.size};i++){grid[i]=&_ppQuadGrid[i*${f.size}];widths[i]=${f.size};}`;call=cpp?'Solution().construct(grid)':`construct(grid,${f.size},widths)`;}
 prefix+=`static int _ppQuadExpected[]={${ar(flat(f.expected))}};`;
 body+=`${P}result=${call};if(!result)return false;${cpp?'std::vector<Node*>queue('+n+',nullptr);':'struct Node**queue=calloc('+n+',sizeof(struct Node*));'}${P}cur;queue[0]=result;for(int i=0;i<${n};i++){cur=queue[i];if(!cur||cur->isLeaf!=(_ppQuadExpected[6*i]!=0))return false;if(cur->isLeaf){if(cur->val!=(_ppQuadExpected[6*i+1]!=0)||cur->topLeft||cur->topRight||cur->bottomLeft||cur->bottomRight)return false;}else{${fields.map((field,k)=>`if(!cur->${field})return false;queue[_ppQuadExpected[6*i+${k+2}]]=cur->${field};`).join('')}}}return true;`;
 return{prefix,body};}
function javaCapture(f){let body='';function constructTree(t,j){body+=`int[]d${j}=${ja(flat(t.nodes))};Node[]input${j}=new Node[${t.nodes.length}];for(int i=0;i<${t.nodes.length};i++)input${j}[i]=new Node(d${j}[6*i+1]!=0,d${j}[6*i]!=0,null,null,null,null);for(int i=0;i<${t.nodes.length};i++){${fields.map((field,k)=>`input${j}[i].${field}=d${j}[6*i+${k+2}]<0?null:input${j}[d${j}[6*i+${k+2}]];`).join('')}}`;}
 let call;if(f.rule.sourceId===558){f.trees.forEach(constructTree);call='new Solution().intersect(input0[0],input1[0])';}else{body+=`int[]cells=${ja(f.grid.flat())};int[][]grid=new int[${f.size}][${f.size}];for(int i=0;i<${f.size};i++)System.arraycopy(cells,i*${f.size},grid[i],0,${f.size});`;call='new Solution().construct(grid)';}
 const n=f.expected.length;body+=`Node result=${call};if(result==null)return false;int[]expected=${ja(flat(f.expected))};Node[]queue=new Node[${n}];queue[0]=result;for(int i=0;i<${n};i++){Node cur=queue[i];if(cur==null||cur.isLeaf!=(expected[6*i]!=0))return false;if(cur.isLeaf){if(cur.val!=(expected[6*i+1]!=0)||cur.topLeft!=null||cur.topRight!=null||cur.bottomLeft!=null||cur.bottomRight!=null)return false;}else{${fields.map((field,k)=>`if(cur.${field}==null)return false;queue[expected[6*i+${k+2}]]=cur.${field};`).join('')}}}return true;`;return body;}
function pythonCapture(f){let body='';for(let j=0;j<f.trees.length;j++){const t=f.trees[j];body+=`        d${j}=${JSON.stringify(flat(t.nodes))}\n        input${j}=[Node(bool(d${j}[6*i+1]),bool(d${j}[6*i]),None,None,None,None) for i in range(${t.nodes.length})]\n        for i,node in enumerate(input${j}):\n`;fields.forEach((field,k)=>body+=`            node.${field}=input${j}[d${j}[6*i+${k+2}]] if d${j}[6*i+${k+2}]>=0 else None\n`);}
 body+=`        result=Solution().${f.rule.sourceId===558?'intersect(input0[0],input1[0])':'construct('+JSON.stringify(f.grid)+')'}\n        expected=${JSON.stringify(flat(f.expected))}\n        queue=[None]*${f.expected.length}; queue[0]=result\n        for i,cur in enumerate(queue):\n            leaf=bool(expected[6*i])\n            if cur is None or type(cur.isLeaf) not in (bool,int) or cur.isLeaf not in (0,1) or bool(cur.isLeaf)!=leaf: return False\n            if leaf:\n                if type(cur.val) not in (bool,int) or cur.val not in (0,1) or bool(cur.val)!=bool(expected[6*i+1]) or any(getattr(cur,field) is not None for field in ${JSON.stringify(fields)}): return False\n            else:\n`;
 fields.forEach((field,k)=>body+=`                if cur.${field} is None: return False\n                queue[expected[6*i+${k+2}]]=cur.${field}\n`);return body+'        return True\n';}
function jsCapture(f,ts,call){let body='';for(let j=0;j<f.trees.length;j++){const t=f.trees[j];body+=`const d${j}=${JSON.stringify(flat(t.nodes))},input${j}=Array.from({length:${t.nodes.length}},(_,i)=>new _Node(!!d${j}[6*i+1],!!d${j}[6*i]));for(let i=0;i<input${j}.length;i++){${fields.map((field,k)=>`input${j}[i].${field}=d${j}[6*i+${k+2}]<0?null:input${j}[d${j}[6*i+${k+2}]];`).join('')}}`;}
 body+=`const result=${call}${f.rule.sourceId===558?'intersect(input0[0],input1[0])':'construct('+JSON.stringify(f.grid)+')'},expected=${JSON.stringify(flat(f.expected))};if(!result)return false;const queue${ts?':(_Node|null)[]':''}=Array(${f.expected.length}).fill(null);queue[0]=result;for(let i=0;i<queue.length;i++){const cur=queue[i],leaf=!!expected[6*i];if(!cur||![false,true,0,1].includes(cur.isLeaf)||!!cur.isLeaf!==leaf)return false;if(leaf){if(![false,true,0,1].includes(cur.val)||!!cur.val!==!!expected[6*i+1]||cur.topLeft!==null||cur.topRight!==null||cur.bottomLeft!==null||cur.bottomRight!==null)return false;}else{${fields.map((field,k)=>`if(!cur.${field})return false;queue[expected[6*i+${k+2}]]=cur.${field};`).join('')}}}return true;`;return body;}
export function prepareQuadNodeSource(language,p,code,input){const f=validateQuadNodeFixture(p,input),active=uncom(code);let prefix='',wrapper='';
 if(['c','cpp'].includes(language)){
  const cpp=language==='cpp';prefix=cpp?(/class\s+Node\s*\{/.test(active)?'':'class Node{public:bool val,isLeaf;Node*topLeft,*topRight,*bottomLeft,*bottomRight;Node(bool v=false,bool l=false,Node*a=nullptr,Node*b=nullptr,Node*c=nullptr,Node*d=nullptr):val(v),isLeaf(l),topLeft(a),topRight(b),bottomLeft(c),bottomRight(d){}};'):(/struct\s+Node\s*\{/.test(active)?'':'struct Node{bool val,isLeaf;struct Node*topLeft,*topRight,*bottomLeft,*bottomRight;};');const generated=nativeCapture(f,cpp);prefix+='\n'+generated.prefix;wrapper=cpp?`class QuadNodeCapture{public:bool captureNode(int seed){${generated.body}}};`:`bool captureNode(int seed){${generated.body}}`;
 }else if(language==='java'){prefix=/class\s+Node\s*\{/.test(active)?'':'class Node{public boolean val,isLeaf;public Node topLeft,topRight,bottomLeft,bottomRight;public Node(){this(false,false);}public Node(boolean v,boolean l){this(v,l,null,null,null,null);}public Node(boolean v,boolean l,Node a,Node b,Node c,Node d){val=v;isLeaf=l;topLeft=a;topRight=b;bottomLeft=c;bottomRight=d;}}';wrapper=`class QuadNodeCapture{public boolean captureNode(int seed){${javaCapture(f)}}}`;
 }else if(language==='python'){prefix=/^class\s+Node\b/m.test(code)?'':'class Node:\n    def __init__(self,val=False,isLeaf=False,topLeft=None,topRight=None,bottomLeft=None,bottomRight=None):\n        self.val,self.isLeaf=val,isLeaf\n        self.topLeft,self.topRight,self.bottomLeft,self.bottomRight=topLeft,topRight,bottomLeft,bottomRight\n';wrapper='class QuadNodeCapture:\n    def captureNode(self,seed):\n'+pythonCapture(f);
 }else if(['javascript','typescript'].includes(language)){const ts=language==='typescript';prefix=/class\s+_Node\s*\{/.test(active)?'':ts?'class _Node{val:boolean;isLeaf:boolean;topLeft:_Node|null;topRight:_Node|null;bottomLeft:_Node|null;bottomRight:_Node|null;constructor(v=false,l=false,a:_Node|null=null,b:_Node|null=null,c:_Node|null=null,d:_Node|null=null){this.val=v;this.isLeaf=l;this.topLeft=a;this.topRight=b;this.bottomLeft=c;this.bottomRight=d;}}':'class _Node{constructor(v=false,l=false,a=null,b=null,c=null,d=null){this.val=v;this.isLeaf=l;this.topLeft=a;this.topRight=b;this.bottomLeft=c;this.bottomRight=d;}}';if(!ts&&!/\b(?:class|function)\s+Node\b/.test(active))prefix+='\nconst Node=_Node;';wrapper=`function captureNode(seed${ts?':number':''}){${jsCapture(f,ts,/class\s+Solution\b/.test(active)?'new Solution().':'')}}`;
 }else throw Error('Unsupported quad language.');
 wrapper=wrapVerifiedNodeCapture(language,wrapper,'QuadNodeCapture',serializeQuadTree(f.expected));
 const joined=language==='java'?code+'\n'+prefix+'\n'+wrapper:prefix+'\n'+code+'\n'+wrapper,contract={className:'QuadNodeCapture',methodName:'captureNode',parameters:[{name:'seed',type:'integer'}],returnType:'string',outputMode:'return',runnerLanguage:language};return materializeFunctionInputPlaceholders(generateFunctionRunnerTemplate(language,contract,joined).replace('{{USER_CODE}}',joined),'seed = 0',contract);
}
