import {additiveExpressionRule,validateAdditiveExpressionFixture,acceptsAdditiveExpressionOutput} from './additiveExpressionFixtureService.js';
import {prepareAdditiveExpressionSource} from './additiveExpressionRunnerService.js';
import {fullBinaryTreeRule,validateFullBinaryTreeInput,acceptsFullBinaryTreeOutput} from './fullBinaryTreeFixtureService.js';
import {prepareFullBinaryTreeSource} from './fullBinaryTreeRunnerService.js';
import {specialHeightRule,validateSpecialHeightFixture,acceptsSpecialHeightOutput} from './specialHeightFixtureService.js';
import {prepareSpecialHeightSource} from './specialHeightRunnerService.js';
import {polynomialRule,validatePolynomialFixture,acceptsPolynomialOutput} from './polynomialFixtureService.js';
import {preparePolynomialSource} from './polynomialRunnerService.js';
import {structuredEmployeeRule,validateStructuredEmployeeFixture,acceptsStructuredEmployeeOutput} from './structuredEmployeeFixtureService.js';
import {prepareStructuredEmployeeSource} from './structuredEmployeeRunnerService.js';
import {splitBstRule,validateSplitBstFixture,acceptsSplitBstOutput} from './splitBstFixtureService.js';
import {prepareSplitBstSource} from './splitBstOriginalNodeRunnerService.js';
import {distanceTreeRule,validateDistanceTreeFixture,acceptsDistanceTreeOutput,prepareDistanceTreeSource} from './distanceTreeSelectorRunnerService.js';
import {remainingProvidedNodeRule,validateRemainingProvidedNodeFixture,validateRemainingProvidedNodeOracle} from './remainingProvidedNodeFixtureService.js';
import {prepareRemainingLinkedSource,acceptsRemainingLinkedOutput} from './remainingProvidedLinkedRunnerService.js';
import {prepareRemainingTreeSource,acceptsRemainingTreeOutput} from './remainingProvidedTreeRunnerService.js';
import {prepareRemainingInteractiveSource,acceptsRemainingInteractiveOutput} from './remainingProvidedInteractiveRunnerService.js';
import {nextCustomNodeRule,validateNextCustomNodeFixture,validateNextCustomNodeOracle} from './nextCustomNodeFixtureService.js';
import {prepareNextNodeScalarSource,acceptsNextNodeScalarOutput} from './nextCustomNodeScalarRunnerService.js';
import {prepareNextNodeStructuralSource,acceptsNextNodeStructuralOutput} from './nextCustomNodeStructuralRunnerService.js';
import{naryNodeRule,validateNaryNodeFixture,acceptsNaryNodeOutput,prepareNaryNodeSource}from'./customNaryNodeRunnerService.js';
import{nextPointerRule,validateNextPointerFixture,validateNextPointerOracle,acceptsNextPointerOutput,prepareNextPointerSource}from'./customNextPointerRunnerService.js';
import{cloneNodeRule,validateCloneNodeFixture,validateCloneNodeOracle,acceptsCloneNodeOutput,prepareCloneNodeSource}from'./customCloneNodeRunnerService.js';
import{quadNodeRule,validateQuadNodeFixture,validateQuadNodeOracle,acceptsQuadNodeOutput,prepareQuadNodeSource}from'./customQuadNodeRunnerService.js';
export function customNodeRule(p){return additiveExpressionRule(p)||fullBinaryTreeRule(p)||specialHeightRule(p)||polynomialRule(p)||structuredEmployeeRule(p)||splitBstRule(p)||distanceTreeRule(p)||remainingProvidedNodeRule(p)||nextCustomNodeRule(p)||naryNodeRule(p)||nextPointerRule(p)||cloneNodeRule(p)||quadNodeRule(p);}
export function validateCustomNodeFixture(p,input){if(additiveExpressionRule(p))return validateAdditiveExpressionFixture(p,input);if(fullBinaryTreeRule(p))return validateFullBinaryTreeInput(p,input);if(specialHeightRule(p))return validateSpecialHeightFixture(p,input);if(polynomialRule(p))return validatePolynomialFixture(p,input);if(structuredEmployeeRule(p))return validateStructuredEmployeeFixture(p,input);if(splitBstRule(p))return validateSplitBstFixture(p,input);if(distanceTreeRule(p))return validateDistanceTreeFixture(p,input);if(remainingProvidedNodeRule(p))return validateRemainingProvidedNodeFixture(p,input);if(nextCustomNodeRule(p))return validateNextCustomNodeFixture(p,input);if(naryNodeRule(p))return validateNaryNodeFixture(p,input);if(nextPointerRule(p))return validateNextPointerFixture(p,input);if(cloneNodeRule(p))return validateCloneNodeFixture(p,input);return validateQuadNodeFixture(p,input);}
export function validateCustomNodeOracle(p,tc){if(additiveExpressionRule(p))return acceptsAdditiveExpressionOutput(p,tc,tc.output)===true;if(fullBinaryTreeRule(p))return acceptsFullBinaryTreeOutput(p,tc,tc.output)===true;if(specialHeightRule(p))return acceptsSpecialHeightOutput(p,tc,tc.output)===true;if(polynomialRule(p))return acceptsPolynomialOutput(p,tc,tc.output)===true;if(structuredEmployeeRule(p))return acceptsStructuredEmployeeOutput(p,tc,tc.output)===true;if(splitBstRule(p))return acceptsSplitBstOutput(p,tc,tc.output)===true;if(distanceTreeRule(p))return acceptsDistanceTreeOutput(p,tc,tc.output)===true;if(remainingProvidedNodeRule(p))return validateRemainingProvidedNodeOracle(p,tc);if(nextCustomNodeRule(p))return validateNextCustomNodeOracle(p,tc);if(naryNodeRule(p))return acceptsNaryNodeOutput(p,tc,tc.output)===true;if(nextPointerRule(p))return validateNextPointerOracle(p,tc);if(cloneNodeRule(p))return validateCloneNodeOracle(p,tc);if(quadNodeRule(p))return validateQuadNodeOracle(p,tc);return false;}
export function acceptsCustomNodeOutput(p,tc,raw){if(additiveExpressionRule(p))return acceptsAdditiveExpressionOutput(p,tc,raw);if(fullBinaryTreeRule(p))return acceptsFullBinaryTreeOutput(p,tc,raw);if(specialHeightRule(p))return acceptsSpecialHeightOutput(p,tc,raw);if(polynomialRule(p))return acceptsPolynomialOutput(p,tc,raw);if(structuredEmployeeRule(p))return acceptsStructuredEmployeeOutput(p,tc,raw);if(splitBstRule(p))return acceptsSplitBstOutput(p,tc,raw);if(distanceTreeRule(p))return acceptsDistanceTreeOutput(p,tc,raw);if(remainingProvidedNodeRule(p))return acceptsRemainingLinkedOutput(p,tc,raw)??acceptsRemainingTreeOutput(p,tc,raw)??acceptsRemainingInteractiveOutput(p,tc,raw);if(nextCustomNodeRule(p))return acceptsNextNodeScalarOutput(p,tc,raw)??acceptsNextNodeStructuralOutput(p,tc,raw);if(naryNodeRule(p))return acceptsNaryNodeOutput(p,tc,raw);if(nextPointerRule(p))return acceptsNextPointerOutput(p,tc,raw);if(cloneNodeRule(p))return acceptsCloneNodeOutput(p,tc,raw);return acceptsQuadNodeOutput(p,tc,raw);}
export function prepareCustomNodeSource(language,p,code,input){if(additiveExpressionRule(p))return prepareAdditiveExpressionSource(language,p,code,input);if(fullBinaryTreeRule(p))return prepareFullBinaryTreeSource(language,p,code,input);if(specialHeightRule(p))return prepareSpecialHeightSource(language,p,code,input);if(polynomialRule(p))return preparePolynomialSource(language,p,code,input);if(structuredEmployeeRule(p))return prepareStructuredEmployeeSource(language,p,code,input);if(splitBstRule(p))return prepareSplitBstSource(language,p,code,input);if(distanceTreeRule(p))return prepareDistanceTreeSource(language,p,code,input);const remaining=remainingProvidedNodeRule(p);if(remaining)return ['rope-character','corresponding-clone'].includes(remaining.kind)?prepareRemainingTreeSource(language,p,code,input):['hidden-grid-unweighted','hidden-grid-weighted','robot-clean'].includes(remaining.kind)?prepareRemainingInteractiveSource(language,p,code,input):prepareRemainingLinkedSource(language,p,code,input);const next=nextCustomNodeRule(p);if(next)return ['nary-diameter','parent-lca','parent-successor','binary-lca-list','binary-nearest'].includes(next.kind)?prepareNextNodeScalarSource(language,p,code,input):prepareNextNodeStructuralSource(language,p,code,input);if(naryNodeRule(p))return prepareNaryNodeSource(language,p,code,input);if(nextPointerRule(p))return prepareNextPointerSource(language,p,code,input);if(cloneNodeRule(p))return prepareCloneNodeSource(language,p,code,input);return prepareQuadNodeSource(language,p,code,input);}
