import {generateFunctionRunnerTemplate} from './functionRunnerTemplateService.js';
import {buildFunctionInputPayload,materializeFunctionInputPlaceholders,parseFunctionTestInput} from './functionTestInputService.js';
export function distanceTreeRule(p){const c=p?.functionContract;return p?.title==='All Nodes Distance K in Binary Tree'&&p.executionMode==='function'&&c?.kind!=='stateful'&&c.className==='Solution'&&c.methodName==='distanceK'&&c.returnType==='integer[]'&&c.outputMode!=='parameter'&&c.parameters?.map(x=>x.name+':'+x.type).join(',')==='root:tree-node,target:tree-node,k:integer'?{kind:'distance-tree-selector'}:null;}
export function validateDistanceTreeFixture(p,input){
 if(!distanceTreeRule(p))throw Error('Exact original-root Distance K contract required');
 const[values,target,k]=buildFunctionInputPayload(input,p.functionContract).args,integer=x=>Number.isInteger(x)&&x>=0&&x<=500;
 if(!Array.isArray(values)||!values.length||!integer(values[0])||!integer(target)||!Number.isInteger(k)||k<0||k>1000)throw Error('Invalid Distance K source bounds');
 const labels=[values[0]],children=[[]],parents=[-1],seen=new Map([[values[0],0]]);let cursor=1;
 for(let i=0;i<labels.length;i++)for(let side=0;side<2&&cursor<values.length;side++){const v=values[cursor++];if(v===null)continue;if(!integer(v)||seen.has(v))throw Error('Ambiguous or invalid original node label');const at=labels.length;seen.set(v,at);labels.push(v);parents.push(i);children.push([]);children[i].push(at);}
 if(labels.length>500||values.slice(cursor).some(v=>v!==null)||!seen.has(target))throw Error('Unreachable node or unknown target selector');
 const queue=[seen.get(target)],distance=Array(labels.length).fill(-1);distance[queue[0]]=0;
 for(let i=0;i<queue.length;i++){const at=queue[i];for(const next of[parents[at],...children[at]])if(next>=0&&distance[next]<0){distance[next]=distance[at]+1;queue.push(next);}}
 return {values,target,k,nodeCount:labels.length,expected:labels.filter((_,i)=>distance[i]===k)};
}
export function acceptsDistanceTreeOutput(p,tc,raw){if(!distanceTreeRule(p))return null;try{const f=validateDistanceTreeFixture(p,tc.input),parsed=parseFunctionTestInput(String(raw).trim()).positional;if(parsed.length!==1||!Array.isArray(parsed[0])||parsed[0].some(x=>!Number.isInteger(x)))return false;const actual=parsed[0].slice().sort((a,b)=>a-b),expected=f.expected.slice().sort((a,b)=>a-b);return actual.length===expected.length&&actual.every((v,i)=>v===expected[i]);}catch{return false;}}
export function prepareDistanceTreeSource(language,p,userCode,input){
 const f=validateDistanceTreeFixture(p,input),method='peerPrepOriginalDistance',className='PeerPrepDistanceAdapter';let code=String(userCode),adapter;
 if(language==='python')adapter=`\ndef ppDistanceSelect(root,value):\n    queue=[root]\n    for node in queue:\n        if node.val==value: return node\n        if node.left is not None: queue.append(node.left)\n        if node.right is not None: queue.append(node.right)\n    raise ValueError('Unknown original node')\nclass ${className}(Solution):\n    def ${method}(self,root,target,k):\n        return self.distanceK(root,ppDistanceSelect(root,target),k)\n`;
 if(language==='javascript'||language==='typescript'){const ts=language==='typescript',any=ts?':any':'',num=ts?':number':'',uncommented=code.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/[^\r\n]*/g,''),call=/\bclass\s+Solution\b/.test(uncommented)?'new Solution().distanceK':'distanceK';adapter=`\nfunction ppDistanceSelect(root${any},value${num})${any}{const queue${any}=[root];for(let i=0;i<queue.length;i++){const node=queue[i];if(node.val===value)return node;if(node.left!=null)queue.push(node.left);if(node.right!=null)queue.push(node.right);}throw Error('Unknown original node');}\nfunction ${method}(root${any},target${num},k${num})${any}{return ${call}(root,ppDistanceSelect(root,target),k);}\n`;}
 if(language==='cpp')adapter=`\nclass ${className}:public Solution{public:static TreeNode* select(TreeNode* root,int value){vector<TreeNode*> queue{root};for(size_t i=0;i<queue.size();i++){auto node=queue[i];if(node->val==value)return node;if(node->left)queue.push_back(node->left);if(node->right)queue.push_back(node->right);}throw runtime_error("Unknown original node");}vector<int> ${method}(TreeNode* root,int target,int k){return distanceK(root,select(root,target),k);}};\n`;
 if(language==='java'){code=code.replace(/(^|\n)\s*public\s+class\s+Solution\b/,'$1class Solution');adapter=`\nclass ${className} extends Solution{static TreeNode select(TreeNode root,int value){java.util.ArrayList<TreeNode> queue=new java.util.ArrayList<>();queue.add(root);for(int i=0;i<queue.size();i++){TreeNode node=queue.get(i);if(node.val==value)return node;if(node.left!=null)queue.add(node.left);if(node.right!=null)queue.add(node.right);}throw new IllegalArgumentException("Unknown original node");}public java.util.List<Integer> ${method}(TreeNode root,int target,int k){return distanceK(root,select(root,target),k);}}\n`;}
 if(language==='c'){code=code.replace(/\bstruct\s+TreeNode\s*\{[^}]*\}\s*;/gs,'');adapter=`\nstatic struct TreeNode* ppDistanceSelect(struct TreeNode* root,int value){struct TreeNode* queue[${f.nodeCount}];int count=1;queue[0]=root;for(int i=0;i<count;i++){struct TreeNode* node=queue[i];if(node->val==value)return node;if(node->left)queue[count++]=node->left;if(node->right)queue[count++]=node->right;}exit(2);}int* ${method}(struct TreeNode* root,int target,int k,int* returnSize){return distanceK(root,ppDistanceSelect(root,target),k,returnSize);}\n`;}
 if(!adapter)throw Error('Distance K requires a supported six-language runner');
 const adapted={...p.functionContract,className,methodName:method,parameters:[{name:'root',type:'tree-node'},{name:'target',type:'integer'},{name:'k',type:'integer'}],runnerLanguage:language},injected=code+adapter,template=generateFunctionRunnerTemplate(language,adapted,injected);
 if(!template)throw Error('Distance K private template unavailable');return materializeFunctionInputPlaceholders(template,input,adapted).replace('{{USER_CODE}}',injected);
}
