import{parseFunctionTestInput,materializeFunctionInputPlaceholders}from'./functionTestInputService.js';import{generateFunctionRunnerTemplate}from'./functionRunnerTemplateService.js';
export const FONT_API={id:'6ac280a219051acf30c4b160',title:'Maximum Font to Fit a Sentence in a Screen',kind:'font',sourceId:1618,methodName:'maxFont',parameters:[{name:'text',type:'string'},{name:'w',type:'integer'},{name:'h',type:'integer'},{name:'fonts',type:'integer[]'},{name:'fontInfo',type:'FontInfo'}]};
export function fontRule(p){const c=p?.functionContract;return p?.title===FONT_API.title&&p.executionMode==='function'&&c?.kind!=='stateful'&&c.className==='Solution'&&c.methodName==='maxFont'&&c.returnType==='integer'&&c.outputMode!=='parameter'&&c.parameters?.length===5&&c.parameters.every((v,i)=>v.name===FONT_API.parameters[i].name&&v.type===FONT_API.parameters[i].type)?FONT_API:null;}
const int=(v,min,max)=>Number.isSafeInteger(v)&&v>=min&&v<=max,metric=(m,size)=>Math.floor(size/m[1])*m[0]+m[2];
export function validateFontFixture(p,input){
 if(!fontRule(p))throw Error('Unsupported FontInfo public contract.');const parsed=parseFunctionTestInput(input),v=parsed.named,names=['text','w','h','fonts','fontInfo'];if(parsed.positional.length||Object.keys(v).length!==5||!names.every(k=>Object.hasOwn(v,k))||typeof v.text!=='string'||!/^[a-z]{1,50000}$/.test(v.text)||!int(v.w,1,10000000)||!int(v.h,1,10000)||!Array.isArray(v.fonts)||!int(v.fonts.length,1,100000)||v.fonts.some((f,i)=>!int(f,1,100000)||(i&&f<=v.fonts[i-1])))throw Error('FontInfo requires legal explicit text/screen/fonts and an authored private metric environment.');
 const f=v.fontInfo,valid=m=>Array.isArray(m)&&m.length===3&&int(m[0],0,21474)&&int(m[1],1,100000)&&int(m[2],0,100000)&&metric(m,1)>0&&metric(m,100000)<=2147483647;
 if(!f||typeof f!=='object'||Object.keys(f).length!==2||!valid(f.height)||!Array.isArray(f.widths)||f.widths.length!==26||!f.widths.every(valid))throw Error('Explicit FontInfo height/26 widths must be monotone [scale,divisor,offset] O(1) integer metrics.');
 const counts=new Array(26).fill(0);for(const ch of v.text)counts[ch.charCodeAt(0)-97]++;let expected=-1;for(const size of v.fonts)if(metric(f.height,size)<=v.h&&counts.reduce((s,c,i)=>s+c*metric(f.widths[i],size),0)<=v.w)expected=size;
 return{rule:FONT_API,...v,expected};
}
export function acceptsFontOutput(p,t,raw){if(!fontRule(p))return undefined;try{const f=validateFontFixture(p,t.input),n=JSON.parse(String(raw).trim());return Number.isInteger(n)&&n===f.expected;}catch{return false;}}
const nativeTriples=f=>`static int _ppFontHeight[]={${f.fontInfo.height}};static int _ppFontWidths[26][3]={${f.fontInfo.widths.map(m=>'{'+m+'}').join(',')}};static int _ppFontMetric(int*m,int size){if(size<1||size>100000){printf("PeerPrep invalid provided API call");exit(0);}return(size/m[1])*m[0]+m[2];}`;
const numbers=a=>{const text=a.join(','),parts=[];for(let i=0;i<text.length;i+=16000)parts.push(JSON.stringify(text.slice(i,i+16000)));return`java.util.Arrays.stream(String.join("",new String[]{${parts.join(',')}}).split(",")).mapToInt(Integer::parseInt).toArray()`;};
export function prepareFontSource(language,p,code,input){
 const f=validateFontFixture(p,input),text=JSON.stringify(f.text),w=f.w,h=f.h,fonts=f.fonts.join(',');let prefix,wrapper;
 if(language==='c'){prefix=nativeTriples(f)+`struct FontInfo{int(*getWidth)(struct FontInfo*,int,char);int(*getHeight)(struct FontInfo*,int);};int _ppFontWidth(struct FontInfo*o,int s,char c){if(c<'a'||c>'z'){printf("PeerPrep invalid provided API call");exit(0);}return _ppFontMetric(_ppFontWidths[c-'a'],s);}int _ppFontH(struct FontInfo*o,int s){return _ppFontMetric(_ppFontHeight,s);}`;wrapper=`int captureApi(int seed){char text[]=${text};int fonts[]={${fonts}};struct FontInfo info={_ppFontWidth,_ppFontH};return maxFont(text,${w},${h},fonts,${f.fonts.length},&info);}`;}
 else if(language==='cpp'){prefix=nativeTriples(f)+`class FontInfo{public:int getWidth(int s,char c){if(c<'a'||c>'z'){printf("PeerPrep invalid provided API call");exit(0);}return _ppFontMetric(_ppFontWidths[c-'a'],s);}int getHeight(int s){return _ppFontMetric(_ppFontHeight,s);}};`;wrapper=`class ProvidedFontCapture{public:int captureApi(int seed){std::vector<int>fonts={${fonts}};FontInfo info;return Solution().maxFont(${text},${w},${h},fonts,info);}};`;}
 else if(language==='java'){prefix=`class FontInfo{private int[]height={${f.fontInfo.height}},widths=${numbers(f.fontInfo.widths.flat())};private int value(int[]a,int offset,int size){if(size<1||size>100000){System.out.print("PeerPrep invalid provided API call");System.exit(0);}return(size/a[offset+1])*a[offset]+a[offset+2];}public int getWidth(int s,char c){if(c<'a'||c>'z'){System.out.print("PeerPrep invalid provided API call");System.exit(0);}return value(widths,(c-'a')*3,s);}public int getHeight(int s){return value(height,0,s);}}`;wrapper=`class ProvidedFontCapture{public int captureApi(int seed){return new Solution().maxFont(${text},${w},${h},${numbers(f.fonts)},new FontInfo());}}`;}
 else if(language==='python'){prefix=`_pp_font_height=${JSON.stringify(f.fontInfo.height)}\n_pp_font_widths=${JSON.stringify(f.fontInfo.widths)}\ndef _pp_font_bad():\n    print('PeerPrep invalid provided API call')\n    raise SystemExit(0)\ndef _pp_font_metric(m,s):\n    if type(s) is not int or not(1<=s<=100000): _pp_font_bad()\n    return (s//m[1])*m[0]+m[2]\nclass FontInfo:\n    def getWidth(self,s,ch):\n        if not isinstance(ch,str) or len(ch)!=1 or not('a'<=ch<='z'): _pp_font_bad()\n        return _pp_font_metric(_pp_font_widths[ord(ch)-97],s)\n    def getHeight(self,s): return _pp_font_metric(_pp_font_height,s)\n`;wrapper=`class ProvidedFontCapture:\n    def captureApi(self,seed):\n        return Solution().maxFont(${text},${w},${h},[${fonts}],FontInfo())\n`;}
 else if(['javascript','typescript'].includes(language)){prefix=`${language==='typescript'?'declare const process:any;':''}const _ppFontHeight=${JSON.stringify(f.fontInfo.height)},_ppFontWidths=${JSON.stringify(f.fontInfo.widths)};function _ppFontBad(){console.log('PeerPrep invalid provided API call');process.exit(0);}function _ppFontMetric(m,s){if(!Number.isInteger(s)||s<1||s>100000)_ppFontBad();return Math.floor(s/m[1])*m[0]+m[2];}class FontInfo{getWidth(s,ch){if(typeof ch!=='string'||!/^[a-z]$/.test(ch))_ppFontBad();return _ppFontMetric(_ppFontWidths[ch.charCodeAt(0)-97],s);}getHeight(s){return _ppFontMetric(_ppFontHeight,s);}}`;wrapper=`function captureApi(seed${language==='typescript'?':number':''}){return ${/\bclass\s+Solution\b/.test(code)?'new Solution().':''}maxFont(${text},${w},${h},[${fonts}],new FontInfo());}`;}
 else throw Error('Unsupported FontInfo language.');
 const user=language==='java'?String(code).replace(/(^|\n)\s*public\s+class\s+Solution\b/,'$1class Solution'):code,joined=prefix+'\n'+user+'\n'+wrapper,contract={className:'ProvidedFontCapture',methodName:'captureApi',parameters:[{name:'seed',type:'integer'}],returnType:'integer',outputMode:'return',runnerLanguage:language};
 return materializeFunctionInputPlaceholders(generateFunctionRunnerTemplate(language,contract,joined),'seed=1',contract).replace('{{USER_CODE}}',joined);
}
