import {validateRemainingProvidedNodeFixture,remainingProvidedNodeRule} from './remainingProvidedNodeFixtureService.js';
import {parseNodeResultEnvelope} from './customNodeResultEnvelopeService.js';
import {finishProvidedCapture,compactJavaInts,withoutDefinitionComments} from './remainingProvidedCaptureService.js';
const kinds=new Set(['rope-character','corresponding-clone']);
export function acceptsRemainingTreeOutput(p,tc,raw){const r=remainingProvidedNodeRule(p);if(!r||!kinds.has(r.kind))return undefined;try{const envelope=parseNodeResultEnvelope(raw);return !!envelope&&JSON.stringify(envelope.value)===JSON.stringify(validateRemainingProvidedNodeFixture(p,tc.input).expected);}catch{return false;}}
export function prepareRemainingTreeSource(language,p,userCode,input) {
 const f=validateRemainingProvidedNodeFixture(p,input),rope=f.rule.kind==='rope-character';if(!kinds.has(f.rule.kind))throw Error('Unsupported remaining tree API.');
 const n=f.values.length,cpp=language==='cpp',ts=language==='typescript',T=rope?'RopeTreeNode':'TreeNode',source=withoutDefinitionComments(userCode);
 let prefix='',body='',wrapper='';
 if(language==='c'||cpp) {
  const ct=cpp?T+'*':'struct '+T+'*',nil=cpp?'nullptr':'NULL';
  if(rope&&!new RegExp((cpp?'class':'struct')+'\\s+RopeTreeNode\\s*\\{').test(source))prefix=cpp?'class RopeTreeNode{public:int len=0;std::string val;RopeTreeNode*left=nullptr,*right=nullptr;};':'struct RopeTreeNode{int len;char*val;struct RopeTreeNode*left,*right;};';
  for(const[k,a]of Object.entries({left:f.left,right:f.right,...(rope?{lengths:f.lengths}:{vals:f.values})}))prefix+=`static int _ppT_${k}[]={${a.length?a.join(','):'0'}};`;
  if(rope)prefix+=`static ${cpp?'const char*':'char*'}_ppT_vals[]={${f.values.map(JSON.stringify).join(',')}};`;
  body=`${ct}nodes[${n}];${rope?'':`${ct}clones[${n}];`}for(int i=0;i<${n};i++){nodes[i]=${cpp?'new '+T+(rope?'()':'(_ppT_vals[i])'):'calloc(1,sizeof(struct '+T+'))'};${rope&&!cpp?'nodes[i]->val=malloc(strlen(_ppT_vals[i])+1);strcpy(nodes[i]->val,_ppT_vals[i]);':'nodes[i]->val=_ppT_vals[i];'}${rope?'nodes[i]->len=_ppT_lengths[i];':`clones[i]=${cpp?'new TreeNode(_ppT_vals[i])':'calloc(1,sizeof(struct TreeNode))'};clones[i]->val=_ppT_vals[i];`}}for(int i=0;i<${n};i++){nodes[i]->left=_ppT_left[i]<0?${nil}:nodes[_ppT_left[i]];nodes[i]->right=_ppT_right[i]<0?${nil}:nodes[_ppT_right[i]];${rope?'':`clones[i]->left=_ppT_left[i]<0?${nil}:clones[_ppT_left[i]];clones[i]->right=_ppT_right[i]<0?${nil}:clones[_ppT_right[i]];`}}`;
  const call=(cpp?'Solution().':'')+f.rule.methodName+'(nodes[0],'+(rope?f.k:`clones[0],nodes[${f.selected}]`)+')';
  if(rope)body+=`char result=${call};return result==${JSON.stringify(f.expected).replaceAll('"',"'")};`;
  else body+=`${ct}result=${call};if(result!=clones[${f.selected}])return false;for(int i=0;i<${n};i++)if(nodes[i]->val!=_ppT_vals[i]||clones[i]->val!=_ppT_vals[i]||nodes[i]->left!=(_ppT_left[i]<0?${nil}:nodes[_ppT_left[i]])||nodes[i]->right!=(_ppT_right[i]<0?${nil}:nodes[_ppT_right[i]])||clones[i]->left!=(_ppT_left[i]<0?${nil}:clones[_ppT_left[i]])||clones[i]->right!=(_ppT_right[i]<0?${nil}:clones[_ppT_right[i]]))return false;return true;`;
  wrapper=cpp?`class RemainingTreeCapture{public:bool captureNode(int seed){${body}}};`:`bool captureNode(int seed){${body}}`;
 }else if(language==='java') {
  if(rope&&!/class\s+RopeTreeNode\s*\{/.test(source))prefix='class RopeTreeNode{public int len;public String val;public RopeTreeNode left,right;public RopeTreeNode(){}}';
  body=`int[]left=${compactJavaInts(f.left)},right=${compactJavaInts(f.right)};${rope?'String[]':'int[]'}vals=${rope?'new String[]{'+f.values.map(JSON.stringify).join(',')+'}':compactJavaInts(f.values)};${rope?'int[]lengths='+compactJavaInts(f.lengths)+';':''}${T}[]nodes=new ${T}[${n}]${rope?'':`,clones=new TreeNode[${n}]`};for(int i=0;i<${n};i++){nodes[i]=new ${T}(${rope?'':'vals[i]'});${rope?'nodes[i].val=vals[i];nodes[i].len=lengths[i];':'clones[i]=new TreeNode(vals[i]);'}}for(int i=0;i<${n};i++){nodes[i].left=left[i]<0?null:nodes[left[i]];nodes[i].right=right[i]<0?null:nodes[right[i]];${rope?'':'clones[i].left=left[i]<0?null:clones[left[i]];clones[i].right=right[i]<0?null:clones[right[i]];'}}`;
  const call=`new Solution().${f.rule.methodName}(nodes[0],${rope?f.k:`clones[0],nodes[${f.selected}]`})`;
  body+=rope?`char result=${call};return result=='${f.expected}';`:`TreeNode result=${call};if(result!=clones[${f.selected}])return false;for(int i=0;i<${n};i++)if(nodes[i].val!=vals[i]||clones[i].val!=vals[i]||nodes[i].left!=(left[i]<0?null:nodes[left[i]])||nodes[i].right!=(right[i]<0?null:nodes[right[i]])||clones[i].left!=(left[i]<0?null:clones[left[i]])||clones[i].right!=(right[i]<0?null:clones[right[i]]))return false;return true;`;
  wrapper=`class RemainingTreeCapture{public boolean captureNode(int seed){${body}}}`;
 }else if(language==='python') {
  if(rope&&!/class\s+RopeTreeNode\s*[:(]/.test(source))prefix='class RopeTreeNode:\n    def __init__(self,len=0,val="",left=None,right=None):\n        self.len=len\n        self.val=val\n        self.left=left\n        self.right=right\n';
  const lines=[`vals=${JSON.stringify(f.values)}`,`left=${JSON.stringify(f.left)}`,`right=${JSON.stringify(f.right)}`,...(rope?[`lengths=${JSON.stringify(f.lengths)}`,'nodes=[RopeTreeNode(lengths[i],v) for i,v in enumerate(vals)]']:['nodes=[TreeNode(v) for v in vals]','clones=[TreeNode(v) for v in vals]']),'for i in range(len(nodes)):','    nodes[i].left=nodes[left[i]] if left[i]>=0 else None','    nodes[i].right=nodes[right[i]] if right[i]>=0 else None',...(rope?[]:['    clones[i].left=clones[left[i]] if left[i]>=0 else None','    clones[i].right=clones[right[i]] if right[i]>=0 else None']),`result=Solution().${f.rule.methodName}(nodes[0],${rope?f.k:`clones[0],nodes[${f.selected}]`})`];
  if(rope)lines.push(`return result==${JSON.stringify(f.expected)}`);
  else lines.push(`if result is not clones[${f.selected}]: return False`,'for i in range(len(nodes)):','    if nodes[i].val!=vals[i] or clones[i].val!=vals[i]: return False','    if nodes[i].left is not (nodes[left[i]] if left[i]>=0 else None) or nodes[i].right is not (nodes[right[i]] if right[i]>=0 else None): return False','    if clones[i].left is not (clones[left[i]] if left[i]>=0 else None) or clones[i].right is not (clones[right[i]] if right[i]>=0 else None): return False','return True');
  wrapper='class RemainingTreeCapture:\n    def captureNode(self,seed):\n'+lines.map(s=>'        '+s).join('\n')+'\n';
 }else if(language==='javascript'||ts) {
  if(rope&&!/class\s+RopeTreeNode\s*\{/.test(source))prefix=ts?'class RopeTreeNode{len:number;val:string;left:RopeTreeNode|null=null;right:RopeTreeNode|null=null;constructor(len=0,val=""){this.len=len;this.val=val;}}':'class RopeTreeNode{constructor(len=0,val=""){this.len=len;this.val=val;this.left=this.right=null;}}';
  body=`const vals=${JSON.stringify(f.values)},left=${JSON.stringify(f.left)},right=${JSON.stringify(f.right)}${rope?',lengths='+JSON.stringify(f.lengths):''};const nodes=vals.map((v,i)=>new ${T}(${rope?'lengths[i],v':'v'}))${rope?'':',clones=vals.map(v=>new TreeNode(v))'};for(let i=0;i<nodes.length;i++){nodes[i].left=left[i]<0?null:nodes[left[i]];nodes[i].right=right[i]<0?null:nodes[right[i]];${rope?'':'clones[i].left=left[i]<0?null:clones[left[i]];clones[i].right=right[i]<0?null:clones[right[i]];'}}`;
  const call=(/class\s+Solution\b/.test(source)?'new Solution().':'')+f.rule.methodName+'(nodes[0],'+(rope?f.k:`clones[0],nodes[${f.selected}]`)+')';
  body+=`const result=${call};`+(rope?`return result===${JSON.stringify(f.expected)};`:`if(result!==clones[${f.selected}])return false;for(let i=0;i<nodes.length;i++)if(nodes[i].val!==vals[i]||clones[i].val!==vals[i]||nodes[i].left!==(left[i]<0?null:nodes[left[i]])||nodes[i].right!==(right[i]<0?null:nodes[right[i]])||clones[i].left!==(left[i]<0?null:clones[left[i]])||clones[i].right!==(right[i]<0?null:clones[right[i]]))return false;return true;`);
  wrapper=`function captureNode(seed${ts?':number':''}){${body}}`;
 }else throw Error('Six requested languages required.');
 return finishProvidedCapture(language,userCode,prefix,wrapper,'RemainingTreeCapture',f.expected);
}
