import {generateFunctionRunnerTemplate} from './functionRunnerTemplateService.js';import {materializeFunctionInputPlaceholders} from './functionTestInputService.js';import {validateSpecialHeightFixture} from './specialHeightFixtureService.js';
export function prepareSpecialHeightSource(language,p,userCode,input){const f=validateSpecialHeightFixture(p,input),method='peerPrepSpecialLeafRingHeight',adapterClass='PeerPrepSpecialHeightAdapter';let code=String(userCode),prefix='',adapter='';
 if(language==='python'){const marker=code.indexOf('# PeerPrep generated function adapter. Keep this section unchanged.');if(marker>=0)code=code.slice(0,marker);prefix='class TreeNode:\n    def __init__(self,val=0,left=None,right=None): self.val=val;self.left=left;self.right=right\n';adapter=`\nclass ${adapterClass}(Solution):\n    def ${method}(self,rows):\n        nodes=[TreeNode(row[0]) for row in rows]\n        for i,row in enumerate(rows):\n            nodes[i].left=nodes[row[1]] if row[1]>=0 else None\n            nodes[i].right=nodes[row[2]] if row[2]>=0 else None\n        return self.heightOfTree(nodes[0])\n`;}
 if(language==='javascript'||language==='typescript'){const ts=language==='typescript',plain=code.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/[^\r\n]*/g,''),call=/\bclass\s+Solution\b/.test(plain)?'new Solution().heightOfTree':'heightOfTree';prefix=ts?'class TreeNode{constructor(public val:number=0,public left:TreeNode|null=null,public right:TreeNode|null=null){}}\n':'class TreeNode{constructor(val=0,left=null,right=null){this.val=val;this.left=left;this.right=right;}}\n';adapter=`\nfunction ${method}(rows${ts?':number[][]':''})${ts?':number':''}{const nodes=rows.map(row=>new TreeNode(row[0]));for(let i=0;i<rows.length;i++){nodes[i].left=rows[i][1]<0?null:nodes[rows[i][1]];nodes[i].right=rows[i][2]<0?null:nodes[rows[i][2]];}return ${call}(nodes[0]);}\n`;}
 if(language==='cpp'){prefix='struct TreeNode{int val;TreeNode*left,*right;TreeNode(int v=0,TreeNode*l=nullptr,TreeNode*r=nullptr):val(v),left(l),right(r){}};\n';adapter=`\nclass ${adapterClass}:public Solution{public:int ${method}(vector<vector<int>>rows){vector<TreeNode*>nodes;for(const auto&row:rows)nodes.push_back(new TreeNode(row[0]));for(size_t i=0;i<rows.size();i++){nodes[i]->left=rows[i][1]<0?nullptr:nodes[rows[i][1]];nodes[i]->right=rows[i][2]<0?nullptr:nodes[rows[i][2]];}return heightOfTree(nodes[0]);}};\n`;}
 if(language==='java'){code=code.replace(/(^|\n)\s*public\s+class\s+Solution\b/,'$1class Solution');prefix='class TreeNode{int val;TreeNode left,right;TreeNode(){this(0);}TreeNode(int v){val=v;}TreeNode(int v,TreeNode l,TreeNode r){val=v;left=l;right=r;}}\n';adapter=`\nclass ${adapterClass} extends Solution{public int ${method}(int[][]rows){TreeNode[]nodes=new TreeNode[rows.length];for(int i=0;i<rows.length;i++)nodes[i]=new TreeNode(rows[i][0]);for(int i=0;i<rows.length;i++){nodes[i].left=rows[i][1]<0?null:nodes[rows[i][1]];nodes[i].right=rows[i][2]<0?null:nodes[rows[i][2]];}return heightOfTree(nodes[0]);}}\n`;}
 if(language==='c'){code=code.replace(/\bstruct\s+TreeNode\s*\{[^}]*\}\s*;/gs,'');adapter=`\nint ${method}(int**rows,int rowsSize,int*rowsColSize){struct TreeNode**nodes=malloc(rowsSize*sizeof(*nodes));for(int i=0;i<rowsSize;i++){nodes[i]=malloc(sizeof(**nodes));nodes[i]->val=rows[i][0];}for(int i=0;i<rowsSize;i++){nodes[i]->left=rows[i][1]<0?NULL:nodes[rows[i][1]];nodes[i]->right=rows[i][2]<0?NULL:nodes[rows[i][2]];}return heightOfTree(nodes[0]);}\n`;}
 if(!adapter)throw Error('Six-language special leaf-ring runner required');const adapted={className:adapterClass,methodName:method,parameters:[{name:'rows',type:'integer[][]'}],returnType:'integer',outputMode:'return',runnerLanguage:language},injected=language==='java'?code+prefix+adapter:prefix+code+adapter,template=generateFunctionRunnerTemplate(language,adapted,injected);if(!template)throw Error('Special tree private numeric runner unavailable');return materializeFunctionInputPlaceholders(template,'rows='+JSON.stringify(f.rows),adapted).replace('{{USER_CODE}}',injected);
}
