import {buildFunctionInputPayload,parseFunctionTestInput} from './functionTestInputService.js';
export function structuredEmployeeContract(kind){return{className:'Solution',kind:'function',methodName:kind==='employee'?'getImportance':'employeeFreeTime',parameters:kind==='employee'?[{name:'employees',type:'employee[]'},{name:'id',type:'integer'}]:[{name:'schedule',type:'interval[][]'}],returnType:kind==='employee'?'integer':'interval[]',outputMode:'return'};}
export function structuredEmployeeRule(p){const c=p?.functionContract;if(p?.executionMode!=='function'||c?.kind==='stateful'||c?.className!=='Solution'||c?.outputMode==='parameter')return null;for(const[kind,title]of[['employee','Employee Importance'],['interval','Employee Free Time']]){const wanted=structuredEmployeeContract(kind);if(p.title===title&&c.methodName===wanted.methodName&&c.returnType===wanted.returnType&&JSON.stringify(c.parameters?.map(x=>[x.name,x.type]))===JSON.stringify(wanted.parameters.map(x=>[x.name,x.type])))return{kind};}return null;}
export function validateStructuredEmployeeFixture(p,input){
 const rule=structuredEmployeeRule(p);if(!rule)throw Error('Exact provided Employee/Interval contract required');const args=buildFunctionInputPayload(input,p.functionContract).args;
 if(rule.kind==='employee'){
  const[employees,id]=args;if(!Array.isArray(employees)||employees.length<1||employees.length>2000||!Number.isInteger(id))throw Error('Source-sized employee collection required');const byId=new Map(),leaders=new Map();
  for(const entry of employees){if(!Array.isArray(entry)||entry.length!==3||!Number.isInteger(entry[0])||entry[0]<1||entry[0]>2000||byId.has(entry[0])||!Number.isInteger(entry[1])||entry[1]<-100||entry[1]>100||!Array.isArray(entry[2])||entry[2].some(x=>!Number.isInteger(x))||new Set(entry[2]).size!==entry[2].length)throw Error('Unique source-bounded employees required');byId.set(entry[0],entry);}
  if(!byId.has(id))throw Error('Existing queried employee required');for(const[e,,subs]of employees)for(const child of subs){if(!byId.has(child)||leaders.has(child))throw Error('Valid subordinate IDs with at most one direct leader required');leaders.set(child,e);}
  const complete=new Set();for(const[e]of employees){const path=new Set();let at=e;while(at!==undefined&&!complete.has(at)){if(path.has(at))throw Error('Cyclic employee hierarchy');path.add(at);at=leaders.get(at);}for(const x of path)complete.add(x);}
  const queue=[id];let expected=0;for(let i=0;i<queue.length;i++){const entry=byId.get(queue[i]);expected+=entry[1];queue.push(...entry[2]);}
  return{kind:rule.kind,rows:employees.map(([e,importance,subs])=>[e,importance,...subs]),id,expected};
 }
 const[schedule]=args;if(!Array.isArray(schedule)||schedule.length<1||schedule.length>50)throw Error('Source employee schedules required');const rows=[],all=[];
 for(let employee=0;employee<schedule.length;employee++){const intervals=schedule[employee];if(!Array.isArray(intervals)||intervals.length<1||intervals.length>50)throw Error('Source-sized nonempty interval lists required');let last=-1;for(const pair of intervals){if(!Array.isArray(pair)||pair.length!==2||pair.some(x=>!Number.isInteger(x))||pair[0]<0||pair[1]>100000000||pair[0]>=pair[1]||pair[0]<last)throw Error('Sorted nonoverlapping positive intervals required');last=pair[1];rows.push([employee,...pair]);all.push(pair);}}
 all.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);const expected=[];let end=all[0][1];for(const[start,next]of all){if(start>end)expected.push([end,start]);end=Math.max(end,next);}return{kind:rule.kind,rows,employeeCount:schedule.length,expected};
}
export function acceptsStructuredEmployeeOutput(p,tc,raw){if(!structuredEmployeeRule(p))return null;try{const f=validateStructuredEmployeeFixture(p,tc.input),values=parseFunctionTestInput(String(raw).trim()).positional;if(values.length!==1)return false;const result=values[0];return f.kind==='employee'?Number.isSafeInteger(result)&&result===f.expected:Array.isArray(result)&&JSON.stringify(result)===JSON.stringify(f.expected);}catch{return false;}}
