import {generateFunctionRunnerTemplate} from './functionRunnerTemplateService.js';import {materializeFunctionInputPlaceholders} from './functionTestInputService.js';import {validateStructuredEmployeeFixture} from './structuredEmployeeFixtureService.js';
export function prepareStructuredEmployeeSource(language,p,userCode,input){
 const f=validateStructuredEmployeeFixture(p,input),method='peerPrepStructuredEmployee',adapterClass='PeerPrepEmployeeAdapter';let code=String(userCode),prefix='',adapter='';
 const employee=f.kind==='employee',ts=language==='typescript';
 if(language==='python'){
  prefix=employee?'class Employee:\n    def __init__(self,id,importance,subordinates): self.id=id;self.importance=importance;self.subordinates=subordinates\n':'class Interval:\n    def __init__(self,start=0,end=0): self.start=start;self.end=end\n';
  adapter=employee?`\nclass ${adapterClass}(Solution):\n    def ${method}(self,rows,id):\n        employees=[Employee(row[0],row[1],row[2:]) for row in rows]\n        return self.getImportance(employees,id)\n`:`\nclass ${adapterClass}(Solution):\n    def ${method}(self,rows,employeeCount):\n        schedule=[[] for _ in range(employeeCount)]\n        for employee,start,end in rows: schedule[employee].append(Interval(start,end))\n        result=self.employeeFreeTime(schedule)\n        if not isinstance(result,(list,tuple)): return [[-1,-1]]\n        return [[interval.start,interval.end] for interval in result]\n`;
 }
 if(language==='javascript'||ts){
  const plain=code.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/[^\r\n]*/g,''),call=/\bclass\s+Solution\b/.test(plain)?'new Solution().'+p.functionContract.methodName:p.functionContract.methodName;
  prefix=employee?(ts?'class Employee{constructor(public id:number,public importance:number,public subordinates:number[]){}}\n':'class Employee{constructor(id,importance,subordinates){this.id=id;this.importance=importance;this.subordinates=subordinates;}}\n'):(ts?'class Interval{constructor(public start:number=0,public end:number=0){}}\n':'class Interval{constructor(start=0,end=0){this.start=start;this.end=end;}}\n');
  const rows=ts?'rows:number[][]':'rows',arg=ts?(employee?'id:number':'employeeCount:number'):(employee?'id':'employeeCount');
  adapter=employee?`\nfunction ${method}(${rows},${arg})${ts?':number':''}{const employees=rows.map(row=>new Employee(row[0],row[1],row.slice(2)));return ${call}(employees,id);}\n`:`\nfunction ${method}(${rows},${arg})${ts?':number[][]':''}{const schedule${ts?':Interval[][]':''}=Array.from({length:employeeCount},()=>[]);for(const row of rows)schedule[row[0]].push(new Interval(row[1],row[2]));const result=${call}(schedule);if(!Array.isArray(result))return [[-1,-1]];return result.map(interval=>[interval.start,interval.end]);}\n`;
 }
 if(language==='cpp'){
  prefix=employee?'class Employee{public:int id,importance;vector<int> subordinates;};\n':'class Interval{public:int start,end;Interval(int s=0,int e=0):start(s),end(e){}};\n';
  adapter=employee?`\nclass ${adapterClass}:public Solution{public:int ${method}(vector<vector<int>> rows,int id){vector<Employee*> employees;for(const auto&row:rows){auto e=new Employee();e->id=row[0];e->importance=row[1];e->subordinates.assign(row.begin()+2,row.end());employees.push_back(e);}return getImportance(employees,id);}};\n`:`\nclass ${adapterClass}:public Solution{public:vector<vector<int>> ${method}(vector<vector<int>> rows,int employeeCount){vector<vector<Interval*>> schedule(employeeCount);for(const auto&row:rows)schedule[row[0]].push_back(new Interval(row[1],row[2]));auto intervals=employeeFreeTime(schedule);vector<vector<int>> result;for(auto interval:intervals){if(!interval)return {{-1,-1}};result.push_back({interval->start,interval->end});}return result;}};\n`;
 }
 if(language==='java'){
  code=code.replace(/(^|\n)\s*public\s+class\s+Solution\b/,'$1class Solution');
  prefix=employee?'class Employee{public int id,importance;public java.util.List<Integer> subordinates;Employee(){this(0,0,new java.util.ArrayList<>());}Employee(int id,int importance,java.util.List<Integer> subordinates){this.id=id;this.importance=importance;this.subordinates=subordinates;}}\n':'class Interval{public int start,end;Interval(){}Interval(int start,int end){this.start=start;this.end=end;}}\n';
  adapter=employee?`\nclass ${adapterClass} extends Solution{public int ${method}(int[][]rows,int id){java.util.List<Employee> employees=new java.util.ArrayList<>();for(int[]row:rows){java.util.List<Integer> subs=new java.util.ArrayList<>();for(int i=2;i<row.length;i++)subs.add(row[i]);employees.add(new Employee(row[0],row[1],subs));}return getImportance(employees,id);}}\n`:`\nclass ${adapterClass} extends Solution{public int[][] ${method}(int[][]rows,int employeeCount){java.util.List<java.util.List<Interval>> schedule=new java.util.ArrayList<>();for(int i=0;i<employeeCount;i++)schedule.add(new java.util.ArrayList<>());for(int[]row:rows)schedule.get(row[0]).add(new Interval(row[1],row[2]));java.util.List<Interval> intervals=employeeFreeTime(schedule);if(intervals==null)return new int[][]{{-1,-1}};int[][]result=new int[intervals.size()][2];for(int i=0;i<result.length;i++){Interval interval=intervals.get(i);if(interval==null)return new int[][]{{-1,-1}};result[i][0]=interval.start;result[i][1]=interval.end;}return result;}}\n`;
 }
 if(language==='c'){
  code=code.replace(/\bstruct\s+(Employee|Interval)\s*\{[^}]*\}\s*;/gs,'');
  prefix=employee?'struct Employee{int id,importance;int*subordinates;int subordinatesSize;};\n':'struct Interval{int start,end;};\n';
  adapter=employee?`\nint ${method}(int**rows,int rowsSize,int*rowsColSize,int id){struct Employee**employees=malloc(rowsSize*sizeof(*employees));for(int i=0;i<rowsSize;i++){employees[i]=malloc(sizeof(**employees));employees[i]->id=rows[i][0];employees[i]->importance=rows[i][1];employees[i]->subordinatesSize=rowsColSize[i]-2;employees[i]->subordinates=malloc((rowsColSize[i]-2)*sizeof(int));for(int j=2;j<rowsColSize[i];j++)employees[i]->subordinates[j-2]=rows[i][j];}return getImportance(employees,rowsSize,id);}\n`:`\nint** ${method}(int**rows,int rowsSize,int*rowsColSize,int employeeCount,int*returnSize,int**returnColumnSizes){int*counts=calloc(employeeCount,sizeof(int)),*at=calloc(employeeCount,sizeof(int));for(int i=0;i<rowsSize;i++)counts[rows[i][0]]++;struct Interval***schedule=malloc(employeeCount*sizeof(*schedule));for(int i=0;i<employeeCount;i++)schedule[i]=malloc(counts[i]*sizeof(**schedule));for(int i=0;i<rowsSize;i++){struct Interval*x=malloc(sizeof(*x));x->start=rows[i][1];x->end=rows[i][2];schedule[rows[i][0]][at[rows[i][0]]++]=x;}int count=0;struct Interval**intervals=employeeFreeTime(schedule,employeeCount,counts,&count);if(count<0||count>rowsSize||(count&&!intervals)){*returnSize=1;*returnColumnSizes=malloc(sizeof(int));(*returnColumnSizes)[0]=2;int**bad=malloc(sizeof(*bad));bad[0]=malloc(2*sizeof(int));bad[0][0]=bad[0][1]=-1;return bad;}*returnSize=count;*returnColumnSizes=malloc(count*sizeof(int));int**result=malloc(count*sizeof(*result));for(int i=0;i<count;i++){(*returnColumnSizes)[i]=2;result[i]=malloc(2*sizeof(int));if(!intervals[i]){result[i][0]=result[i][1]=-1;}else{result[i][0]=intervals[i]->start;result[i][1]=intervals[i]->end;}}return result;}\n`;
 }
 if(!adapter)throw Error('Six-language Employee/Interval runner required');
 const argument=employee?{name:'id',type:'integer'}:{name:'employeeCount',type:'integer'},adapted={className:adapterClass,methodName:method,parameters:[{name:'rows',type:'integer[][]'},argument],returnType:employee?'integer':'integer[][]',outputMode:'return',runnerLanguage:language},privateInput='rows='+JSON.stringify(f.rows)+','+argument.name+'='+(employee?f.id:f.employeeCount),injected=language==='java'?code+prefix+adapter:prefix+code+adapter;
 const template=generateFunctionRunnerTemplate(language,adapted,injected);if(!template)throw Error('Structured Employee/Interval runner unavailable');return materializeFunctionInputPlaceholders(template,privateInput,adapted).replace('{{USER_CODE}}',injected);
}
