import { Router } from 'express';
import authRoutes from './auth.js';
import studentRoutes from './students.js';
import eventRoutes from './events.js';
import pairingRoutes from './pairing.js';
import scheduleRoutes from './schedule.js';
import feedbackRoutes from './feedback.js';
import coordinatorRoutes from './coordinators.js';
import subjectRoutes from './subjects.js';
import learningRoutes from './learning.js';
import activityRoutes from './activity.js';
import compilerRoutes from './compiler.js';
import adminAssessmentRoutes from './adminAssessment.js';
import studentAssessmentRoutes from './studentAssessment.js';
import emailTemplateRoutes from './emailTemplates.js';
import notificationRoutes from './notifications.js';
import announcementAdminRoutes from './announcementsAdmin.js';
import announcementStudentRoutes from './announcementsStudent.js';

const router = Router();
router.use('/auth', authRoutes);
router.use('/students', studentRoutes);
router.use('/events', eventRoutes);
router.use('/pairing', pairingRoutes);
router.use('/schedule', scheduleRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/coordinators', coordinatorRoutes);
router.use('/subjects', subjectRoutes);
router.use('/learning', learningRoutes);
router.use('/activity', activityRoutes);
router.use('/compiler', compilerRoutes);
router.use('/admin', adminAssessmentRoutes);
router.use('/student', studentAssessmentRoutes);
router.use('/email-templates', emailTemplateRoutes);
router.use('/notifications', notificationRoutes);
router.use('/admin/announcements', announcementAdminRoutes);
router.use('/student/announcements', announcementStudentRoutes);

export default router;
