import { Router } from 'express';
import authRoutes from './auth.js';
import studentRoutes from './students.js';
import eventRoutes from './events.js';
import pairingRoutes from './pairing.js';
import scheduleRoutes from './schedule.js';
import feedbackRoutes from './feedback.js';
import coordinatorRoutes from './coordinators.js';
import subjectRoutes from './subjects.js';
import learningRoutes from './learning.js';
import activityRoutes from './activity.js';
import compilerRoutes from './compiler.js';
import adminAssessmentRoutes from './adminAssessment.js';
import studentAssessmentRoutes from './studentAssessment.js';
import emailTemplateRoutes from './emailTemplates.js';
import notificationRoutes from './notifications.js';
import announcementAdminRoutes from './announcementsAdmin.js';
import announcementStudentRoutes from './announcementsStudent.js';
import companyInsightsRoutes from './companyInsights.js';
import studentAnalysisRoutes from './studentAnalysis.js';
import resultsRoutes from './results.js';
import executeRoutes from './execute.js';
import mailQueueRoutes from './mailQueue.js';
import resumeRoutes from './resume.js';
import assessmentFeedbackRoutes from './assessmentFeedback.js';
import masterDataRoutes from './masterData.js';
import { requireAuth, requireFullStudent } from '../middleware/auth.js';

const router = Router();
router.use('/auth', authRoutes);
router.use('/students', requireAuth, requireFullStudent, studentRoutes);
router.use('/events', requireAuth, requireFullStudent, eventRoutes);
router.use('/pairing', requireAuth, requireFullStudent, pairingRoutes);
router.use('/schedule', requireAuth, requireFullStudent, scheduleRoutes);
router.use('/feedback', requireAuth, requireFullStudent, feedbackRoutes);
router.use('/coordinators', coordinatorRoutes);
router.use('/subjects', requireAuth, requireFullStudent, subjectRoutes);
router.use('/learning', requireAuth, requireFullStudent, learningRoutes);
router.use('/activity', requireAuth, requireFullStudent, activityRoutes);
router.use('/compiler', requireAuth, requireFullStudent, compilerRoutes);
router.use('/admin', adminAssessmentRoutes);
router.use('/student', studentAssessmentRoutes);
router.use('/email-templates', emailTemplateRoutes);
router.use('/notifications', notificationRoutes);
router.use('/admin/announcements', announcementAdminRoutes);
router.use('/student/announcements', requireAuth, requireFullStudent, announcementStudentRoutes);
router.use('/admin/company-insights', companyInsightsRoutes);
router.use('/student/analysis', requireAuth, requireFullStudent, studentAnalysisRoutes);
router.use('/results', resultsRoutes);
router.use('/execute', executeRoutes);
router.use('/mail-queue', mailQueueRoutes);
router.use('/resume', requireAuth, requireFullStudent, resumeRoutes);
router.use('/assessment-feedback', assessmentFeedbackRoutes);
router.use('/master-data', masterDataRoutes);

export default router;
